name: markdown_quill
description: Convert between quill (delta) format and markdown
version: 0.0.1+1
repository: https://github.com/TarekkMA/markdown_quill

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  charcode: ^1.3.1
  collection: ^1.15.0
  flutter_quill: ^4.0.1
  markdown: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  meta: ^1.7.0
  very_good_analysis: ^2.4.0
